name: fireshipCourse
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: 2.14.0
  cloud_firestore: 4.8.1
  firebase_auth: 4.6.3
  firebase_core_platform_interface: 4.8.0
  google_sign_in: 5.3.3
  sign_in_with_apple: 4.0.0
  crypto: 3.0.1
  font_awesome_flutter: 10.1.0
  google_fonts: 5.1.0
  provider: 6.0.3
  rxdart: 0.27.4
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: 2.4.6
  json_serializable: 6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif
